config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    get 'omniauth_callbacks/vkontakte'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end
  #resources :users
  resources :posts
  get 'profile/index'

  get 'home/index'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  validates_associated :user
end

app/models/mark.rb
class Mark < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  validates_associated :user
  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:vkontakte]
  has_many :posts
  validates :email, uniqueness: true, length: {minimum: 3}
  validates :name, uniqueness: true, length: {in: 6..50}

  def self.find_for_vkontakte_oauth access_token
    if user = User.where(:url => access_token.info.urls.Vkontakte).first
      user
    else 
      User.create!(:provider => access_token.provider, :url => access_token.info.urls.Vkontakte, :username => access_token.info.name, :nickname => access_token.extra.raw_info.domain, :email => access_token.extra.raw_info.domain+'@vk.com', :password => Devise.friendly_token[0,20]) 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  
  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.page(params[:page]).per(2)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.fetch(:post, {})
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < ApplicationController
  def vkontakte
  	@user = User.find_for_vkontakte_oauth request.env["omniauth.auth"]
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :moderator, :creator, :disactive)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/home/index.html.slim
h1 Что тут можно найти?

p Пополнить счёт в любом отделении Казпочты могут теперь пользователи "Яндекс.Денег", для этого нужно предъявить паспорт и номер счёта в "Яндекс.Деньгах".
|Такая возможность осуществлена благодаря ключевому партнеру Яндекс.Деньги в Республике Казахстан - PayBox!
|Раньше казахстанские пользователи могли пополнить электронный кошелёк только с банковской карты. Теперь это можно сделать в любом из более чем 2900 отделений Казпочты по всей стране – достаточно прийти туда с паспортом и назвать номер счёта в "Яндекс.Деньгах".
|Чтобы воспользоваться всеми преимуществами кошелька, казахстанским пользователям необходимо пройти идентификацию. Для этого нужно отправить в "Яндекс.Деньги" заявление по почте или обратиться с ним к одному из представителей сервиса в Алматы, Астане или Караганде.
|Популярность онлайн-оплаты среди жителей Казахстана стремительно растёт. За 2016 год пользователи совершили около 33 млн таких платежей – это более чем вдвое превышает аналогичный показатель 2015 года. В прошлом году общий объём онлайн-платежей за товары и услуги составил 307 млрд тенге – в 3,4 раза больше, чем годом ранее.
p
  span Это и многое другое можно найти в моем блоге

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_pack_tag "application"
    
    = csrf_meta_tag

  body
    = render 'shared/header'
          
    .row
      .medium-8.columns
        == yield
      .medium-4.columns
        .sticky
          h4
            | Categories
          ul
            li
              a[href="#"]
                | Skyler
            li
              a[href="#"]
                | Jesse
            li
              a[href="#"]
                | Mike
            li
              a[href="#"]
                | Holly
          h4
            | Authors
          ul
            li
              a[href="#"]
                | Skyler
            li
              a[href="#"]
                | Jesse
            li
              a[href="#"]
                | Mike
            li
              a[href="#"]
                | Holly
    = javascript_pack_tag "application"

app/views/posts/_comment.html.slim
p = comment.body.html_safe
hr

app/views/posts/_form.html.slim
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      h2 = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - @post.errors.full_messages.each do |message|
          li = message

  .actions = f.submit

app/views/posts/_post.html.slim
.blog-post
  h3 = post.title 
    small 3/6/2015
  img.thumbnail src="http://placehold.it/850x350"
  p = post.body
  .callout
    ul.menu.simple
      li
        a href="#" Author:  #{post.user.name}
      li
        a href="#" Comments: #{post.comments.count} 

app/views/posts/edit.html.slim
h1 Editing post

== render 'form'

=> link_to 'Show', @post
'|
=< link_to 'Back', posts_path

app/views/posts/index.html.slim
= render partial: 'post', collection: @posts

app/views/posts/new.html.slim
h1 New post

== render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice

= render partial: 'post', locals: {post: @post}

#comments
	= render partial: 'comment', collection: @comments
	.row.column
		= paginate @comments

app/views/shared/_footer.html.slim
footer По всем вопросам Вы можете обращаться к вашему персональному менеджеру

app/views/shared/_header.html.slim
.top-bar
  .top-bar-left
    ul.menu
      li.menu-text
        | Yeti Agency
  .top-bar-right
    ul.menu
      - if user_signed_in?
        li = link_to current_user.name, edit_user_registration_path
        li = link_to t('actions.log_out'), destroy_user_session_path, method: :delete
      - else
        li = link_to t('actions.sign_in'), new_user_session_path
        li = link_to t('actions.sign_in_with', name: 'Vkontakte'), user_vkontakte_omniauth_authorize_path
        li = link_to t('actions.sign_up'), new_user_registration_path

app/views/users/_form.html.slim
= form_for @user, html:{class: "grid-x grid-padding-x	"} do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message
  = content_tag :lable do
  	| Имя 
  	= f.text_field :name
	= content_tag :lable do
		| Email
		= f.text_field :email
	= content_tag :div, class: "large-6 cell" 
		= f.check_box :moderator
		= content_tag :lable, "Модератор"
	= content_tag :div, class: "large-6 cell" 
		= f.check_box :creator
		= content_tag :lable, "Создатель"
	= content_tag :div, class: "large-6 cell" 
		= f.check_box :disactive
		= content_tag :lable, "Активировать"
  .actions = f.submit

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Имя
      th Email
      th 
      th
      

  tbody
    - @users.each do |user|
      tr
        td = user.name
        td = user.email
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice


=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path